export const dummyCategoryUser: any = [
  "Customers",
  "Author",
  "Super Admin",
  "BDE",
  "Advisor",
  "Admin Office",
  "Principal",
  "Principal LMI",
  "Bank Officer",
  "Bank Admin",
  "Bank Principal",
];
export const dummyDataTable: any = [
  {
    id: 1,
    name: "Dummy",
    email: "email",
    phone: +628238830283,
    category: "Customers",
    office: "default",
    status: true,
  },
  {
    id: 2,
    name: "Dmmy",
    email: "email",
    phone: +628238830283,
    category: "Customers",
    office: "default",
    status: true,
  },
  {
    id: 3,
    name: "Dmy",
    email: "email",
    phone: +628238830283,
    category: "Advisor",
    office: "default",
    status: true,
  },
  {
    id: 4,
    name: "David",
    email: "email",
    phone: +6282345283,
    category: "Author",
    office: "default",
    status: true,
  },
  {
    id: 5,
    name: "asep",
    email: "emailku",
    phone: +628234534283,
    category: "Author",
    office: "default",
    status: true,
  },
];


